### ISSUE TITLE
Secrets scanned do not exclude examples

### ISSUE THREAD

**Issue by ovitente** [reviewdog/action-detect-secrets#61]
I have `.env-local` and `.env-example`.
And your action is being triggered on it. And it don't let me merge PR with all greens.

Is there options to exclude some files from scan?

**Comment by javierjulio** [comment]
@ovitente yes, there is. This can be done a few ways. You can use an inline comment as noted in the README. The other is to specify CLI flags through the `detect_secrets_flags` input. The CLI supports excluding secrets or files. My suggestion is to use a common set of dummy secret values rather than specify entire files or comments to exclude secrets. For example, Postgres and Redis use `postgres` and `guest` typically for default or development logins. Through the CLI it would be set as `----exclude-secrets ^(guest|postgres|sample)$` and the tool will ignore those false positives.

**Comment by levonet** [comment]
@ovitente Of course it is. There are different ways.
You can use `detect_secrets_flags` with detect-secrets options `--exclude-files` or `--exclude-lines`.
Other way is using pragma. See [examples](https://github.com/reviewdog/action-detect-secrets?tab=readme-ov-file#false-positives)

**Comment by ovitente** [comment]
Thank you, I will try it.
But it would be handy if you would add some excluding examples to the readme, for using in github actions.

Right now I have already used a workaround, while using makefile I just generate .env file using templating values)
